# Unbind the default prefix (Ctrl-b)
unbind C-b
# Set the new prefix to Ctrl-t
set -g prefix C-t

# Move status bar to top
set -g status-position top

# Minimalistic styling
set -g status-style "bg=default,fg=default"

set -g status-left "#[fg=color15] #S #[fg=color2]| "
set -g status-right "#{pomodoro_status}"

set -g window-status-format "#[fg=color7] #I:#W"
set -g window-status-current-format "#[fg=color3,bold] #I:#W"
# 󰈸󰜗

set -g status-justify left
set -g status-right-length 20
set -g status-left-length 20

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Extended keys (to use Shift + Enter, Ctrl + Enter, etc.)
set -g extended-keys on
set -g extended-keys-format csi-u

# Use vi keys in buffer
set -g mode-keys vi

# Custom bindings for pane navigation and resizing

# Navigate panes with Ctrl-t + h/j/k/l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Navigate panes with Alt + h/j/k/l
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Move pane up/down with Ctrl-t + J/K
bind-key 'K' swap-pane -U
bind-key 'J' swap-pane -D

# Resize panes with Ctrl-t + Ctrl-h/j/k/l
bind-key -r C-h resize-pane -L 4
bind-key -r C-j resize-pane -D 4
bind-key -r C-k resize-pane -U 4
bind-key -r C-l resize-pane -R 4

# Open new panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Open new windows in current directory
bind-key c new-window -c "#{pane_current_path}"

# Switch to next/previous window with Alt-n/p
bind -n M-n next-window
bind -n M-p previous-window

# Move window right/left with Ctrl-t + N/P
bind-key 'P' swap-window -t -1\; select-window -t -1
bind-key 'N' swap-window -t +1\; select-window -t +1

# Use system's clipboard
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"
# Prefix + y for copy mode
bind-key y copy-mode


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'olimorris/tmux-pomodoro-plus'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# Pomodoro Plus settings
set -g @pomodoro_toggle 'p'
set -g @pomodoro_cancel Escape
set -g @pomodoro_skip '_'

set -g @pomodoro_mins 50
set -g @pomodoro_break_mins 20
set -g @pomodoro_intervals 2
set -g @pomodoro_long_break_mins 20

# Automatically repeat the Pomodoros?
set -g @pomodoro_repeat 'off'
set -g @pomodoro_disable_breaks 'off'

set -g @pomodoro_on " 🍅 "
set -g @pomodoro_complete " ✔︎ "
set -g @pomodoro_pause " ⏸︎ "
set -g @pomodoro_prompt_break " ⏲︎ break? "
set -g @pomodoro_prompt_pomodoro " ⏱︎ start? "

set -g @pomodoro_menu_position "R"
set -g @pomodoro_sound 'play -n synth 0.05 sine 2000 fade h 0.01 0.05 0.01 pad 0 0.05 repeat 20'

set -g @pomodoro_notifications 'on'
# Enables MM:SS (ex: 00:10) format instead of the default (ex: 1m)
set -g @pomodoro_granularity 'off'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
